# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(140300)
$foreground = rgb(B4AEB7)
$color0 = rgb(3E322F)
$color1 = rgb(9B4A74)
$color2 = rgb(633A73)
$color3 = rgb(563264)
$color4 = rgb(4F262A)
$color5 = rgb(24152A)
$color6 = rgb(1F1326)
$color7 = rgb(8C8490)
$color8 = rgb(625C65)
$color9 = rgb(CF639B)
$color10 = rgb(844D99)
$color11 = rgb(734386)
$color12 = rgb(693338)
$color13 = rgb(301C38)
$color14 = rgb(2A1932)
$color15 = rgb(8C8490)
