# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(D6D0D5)
$foreground = rgb(583932)
$color0 = rgb(BAB4BA)
$color1 = rgb(120212)
$color2 = rgb(543570)
$color3 = rgb(543571)
$color4 = rgb(A24B74)
$color5 = rgb(A24B74)
$color6 = rgb(935F53)
$color7 = rgb(583932)
$color8 = rgb(231423)
$color9 = rgb(180319)
$color10 = rgb(704696)
$color11 = rgb(704696)
$color12 = rgb(D8649A)
$color13 = rgb(D8649A)
$color14 = rgb(C47F6F)
$color15 = rgb(1D1311)
