# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
# /* wallust template - gruvbox */ 

$background = rgb(272727)
$foreground = rgb(ebdbb2)
$color0 = rgb(272727)
$color1 = rgb(cc241d)
$color2 = rgb(98971a)
$color3 = rgb(d79920)
$color4 = rgb(448488)
$color5 = rgb(b16186)
$color6 = rgb(689d6a)
$color7 = rgb(a89984)
$color8 = rgb(928374)
$color9 = rgb(fb4833)
$color10 = rgb(b8ba25)
$color11 = rgb(fabc2e)
$color12 = rgb(83a598)
$color13 = rgb(d3869b)
$color14 = rgb(8ec07b)
$color15 = rgb(ebdbb2)
