# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #583932
background         #D6D0D5
cursor             #644064

active_tab_foreground     #D6D0D5
active_tab_background     #583932
inactive_tab_foreground   #583932
inactive_tab_background   #D6D0D5

active_border_color   #583932
inactive_border_color #D6D0D5
bell_border_color     #120212

color0      #BAB4BA
color1		#120212
color2		#543570
color3		#543571
color4		#A24B74
color5		#A24B74
color6		#935F53
color7		#583932
color8		#231423
color9		#180319
color10		#704696
color11		#704696
color12		#D8649A
color13		#D8649A
color14		#C47F6F
color15		#1D1311
