# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = discord &
exec-once = awww-daemon &
exec-once = ABDownloadManager &
exec-once = discord &
exec-once = $HOME/.config/hypr/scripts/monitor-watch.sh
