# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = discord &
exec-once = sh -c 'sleep 1; awww img "$HOME/.config/hypr/wallpaper_effects/.wallpaper_current"'
exec-once = ABDownloadManager &
exec-once = $HOME/.config/hypr/scripts/monitor-watch.sh
