# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

# Border colors for fullscreen states
windowrule = border_color rgb(FB4934) rgb(FB4934), match:fullscreen 1

# Zen browser - transparent with blur
windowrule = match:class ^(zen-alpha|zen)$, opacity 0.8 0.7
windowrule = match:class ^(zen-alpha|zen)$, no_blur off
