# Ctrl+N → Down Arrow, Ctrl+P → Up Arrow
# Escape → ` (backtick), Shift+Escape → ~ (tilde)
# For keyd

[ids]
*

[main]
control = layer(control)

[control]
n = down
p = up

[main]
escape = `
shift(escape) = ~
capslock = escape

