# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ":email"
    replace: "webbacillus@gmail.com"

  - trigger: ":ename"
    replace: "Pasit Khumsena"

  - trigger: ":tname"
    replace: "พสิษฐ์ คำเสนา"

  - trigger: ":phone"
    replace: "0918683540"

  - trigger: ":sid"
    replace: "6633162221"

  - trigger: ":id"
    replace: "1449900785007"

  - trigger: ":address"
    replace: "38 ซอยเกษมสันต์1 แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร 10330"
    

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d %b %Y, %A"



  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Print the current time
  - trigger: ":now"
    replace: "{{current_time}}"
    vars:
      - name: current_time
        type: date
        params:
          format: "%H:%M"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
